### ISSUE TITLE
Doesn't work if `import type` is used for the Model value

### ISSUE THREAD

**Issue by Julien-R44** [adonisjs/route-model-binding#1]
With the following code, if I do an "import type" for the model, and I print "Auction" in my controller, only the id, and thus what is passed in my route params, will be displayed : 

```ts
import { bind } from '@adonisjs/route-model-binding'
import type Auction from 'App/Models/Auction'

export default class BidsController {
  @bind()
  public async show({}, auction: Auction) {
    console.log(auction) // Only print the id
    return { auction }
  }
}
```

However, the following code works correctly, the whole model is printed : 

```ts
import { bind } from '@adonisjs/route-model-binding'
import Auction from 'App/Models/Auction'

export default class BidsController {
  @bind()
  public async show({}, auction: Auction) {
    console.log(auction) // Print the whole model as expected
    return { auction }
  }
}
```

So, sorry I'm really not very familiar with decorators and reflection in Typescript. I guess that must be one of the limitations but I was wondering if you noticed that? And if there is maybe a solution to keep the `import type` ? 

If it is indeed a limitation and nothing can be done about it, I will modify the documentation here : https://github.com/adonisjs/docs.adonisjs.com/pull/193

Let me know if there is anything I can do to help. I didn't have time to investigate right now but I could this weekend if necessary.

**Comment by thetutlage** [comment]
Yeah, that will not work, because types are removed at runtime and there is nothing for the container to resolve or construct

**Comment by Julien-R44** [comment]
Okay thanks, indeed that makes sense! 

It bothered me mostly because of the `@typescript-eslint/consistent-type-imports` ESLint rule which automatically converted my imports into `import type`.
But I just realized that I had not enabled the type-aware linting : 
https://typescript-eslint.io/docs/linting/typed-linting/

It's all good now!
This may be useful for future readers.
